name: Claude Code Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request:
    types: [opened, synchronize]

jobs:
  # ─────────────────────────────────────────────
  # Job 1: Respond to @claude mentions in comments
  # ─────────────────────────────────────────────
  claude-on-mention:
    name: Claude – Respond to @claude
    if: |
      (github.event_name == 'issue_comment' || github.event_name == 'pull_request_review_comment') &&
      contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Optional: set a max number of turns Claude can take
          # max_turns: 5

  # ─────────────────────────────────────────────
  # Job 2: Auto-review PRs when opened
  # ─────────────────────────────────────────────
  claude-pr-review:
    name: Claude – Auto PR Review
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude Code Action (PR Review)
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Prompt Claude to review the PR automatically
          direct_prompt: |
            Please review this pull request. Check for:
            - Bugs or logic errors
            - Security vulnerabilities
            - Code style inconsistencies (refer to CLAUDE.md)
            - Missing tests
            - Documentation gaps
            
            Be constructive and specific. Suggest improvements where applicable.
            If the PR looks good, say so clearly.
